Все ТЗ группового проекта Спринта 12 выполнены
VasilyNS/java-filmorate pull request #21
Opened 2023-04-15 08:01 UTC by VasilyNS

Большая работа, но мы справились. Тесты постмана проходят.

2023-04-16 07:24 UTC, krylov-sergey-sergeevich requested changes
**Привет**

**Логи**
1) Вот вы выбрали алгоритмы которые хотите реализовать, я как ревьювер могу искать и проверять что все есть, но в реальном мире все алгоритмы имеют название/номер чаще и то и то, например у меня на работе дают названия на подобии TS-1 TS-2 TS-3 в документации соответственно есть эти же номера, а далее в коде в логах мы пишем "TS-1 создание того того" и если у кого-то есть вопрос по реализации он идет в документацию и ищет по номеру алгоритма. Итого: Просьба в реадми + в описание PR пронумеровать алгоритмы и добавить в логах соответствующие номера.

2) Так -же в readme следует указать кто какие алгоритмы реализовывал.

3) Во всех контроллерах обязательно должны быть логи

**Структура проекта**

1) Все операции из контроллера должны идти в сервис , а не в DAO. Просьба проверить и поправить.

**Утилиты**

Instant.now() - рекомендую создать отдельный класс DateUtils и будем создавать объекты времени через него, это позволит унифицировать способ получения времени и если будут правки делать их в 1 месте.

DateUtils.now()

Буду ждать с правками =)

2023-04-16 07:24 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        return null;
Может пустой список а не null? Но не обязательно, вдруг там по тестам ограничения  есть

2023-04-16 14:18 UTC, TattletaleStrangler commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        return null;
исправлено

2023-04-17 13:57 UTC, VasilyNS commented
Сергей, привет!

Все твои замечания исправлены! )

Логи:

1. Везде в логах добавили к сообщению коды алгоритмов, они сформированы по инициалам их авторов и порядковому номеру алгоритма, например "(VS17) List of all directors has been sent"
2. В README.md добавили разделы со списком всех алгоритмов по их разработчикам. Каждому алгоритму также добавлено небольшое описание.
3. Добавили в контроллеры недостающие выводы в лог. Чтобы не перегружать методы контроллеров, вывод в лог ведется на слое dao. В данном проекте вывод в лог на слое dao было принято стандартом и согласовано с тобой в Спринте 11. Обсуждение было тут: https://github.com/VasilyNS/java-filmorate/pull/6

Структура проекта:

1. Исправлено, все операции из контроллеров теперь идут в сервисный слой

Утилиты:

Создан класс DateUtils в пакете util, для унификации работы с датой-временем.

2023-04-19 04:10 UTC, krylov-sergey-sergeevich requested changes
Привет, вижу правки - извиняюсь за задержку

**Это не нужно переделывать, просто мысли**
1) Рекомендую логи с индентификатором алгоритма делать до запроса в бд тк если у вас что-то упадет в бд вы даже не узнаете какой алгоритм виноват в ошибках 

2) Когда пишете sql запрос лучше разбивать его на логические блоки по строкам, а то тяжко читать по 1 слову на строке

Что можете поправить если есть время и желание:

1) id - это плохое название переменной в методах, у нас десятки сущностей и у каждой айди и зачем делать предположение что это допустим директор_айди если можно так сразу написать. А в реальном приложение этих айди бывает еще по 2-3 у каждой сущности вообще будет больно.

2) В именах методов сервиса я рекомендую делать так find - возвращает или объект или null, а get возвращает всегда объект или исключение. Это дает стандарт для команды разработки и понимание как ведет себя метод.

Написал что можно исправить/улучшить, но в целом если есть усталость или сроки горят работа, то можете не переживать работа готова для зачета - так что исправляйте на что есть время и буду ждать с правками =)

2023-04-19 04:10 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +            return create(review);
Вот тут если глянуть то выходит мы в этом методе получили film + user и при создание еще раз пойдем получать = двойная работа

если не прав поправьте

2023-04-19 04:10 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +    public Review findById(int reviewId) {
метод более поход на get

2023-04-19 08:03 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +            return create(review);
согласен. перенес в блок else if

2023-04-19 08:06 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +    public Review findById(int reviewId) {
по мне - масло масляное. но поменял

2023-04-19 18:43 UTC, TattletaleStrangler commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +    private List<Film> getDifferentFilmsBetweenUsers(int fromUserId, int toUserId) {
спасибо за хороший пример составления запроса со множеством переменных без использования StringBuilder и циклов!

2023-04-19 18:45 UTC, TattletaleStrangler commented on src/main/java/ru/yandex/practicum/filmorate/Constants.java
> +    public static final String SEARCH_FILM_BY_DIRECTOR = "director";
исправил

2023-04-19 19:30 UTC, VasilyNS commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        userService.getById(id); //если пользователя нет - выкинет ошибку
Убрали, сделал нормальную проверку в сервисе!

2023-04-19 19:31 UTC, VasilyNS commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +    public Review findById(int reviewId) {
Исправлено!

2023-04-19 19:34 UTC, VasilyNS commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +            return create(review);
Поменял на checkUser

2023-04-19 19:35 UTC, VasilyNS commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +    private List<Film> getDifferentFilmsBetweenUsers(int fromUserId, int toUserId) {
Интересный вариант, приняли к сведенью!

2023-04-19 19:38 UTC, VasilyNS commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        List<Integer> userIdWithMaxCommonFilms = findUserIdWithMaxCommonFilms(userId);
Да, вероятно в методе findUserIdWithMaxCommonFilms нужно конечно возвращать не List, а конкретное значение. И проверки на длинну массива деласть в том же findUserIdWithMaxCommonFilms. Передал это разработчику данного алгоритма!

2023-04-19 19:40 UTC, VasilyNS commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public List<Film> getRecommendations(@PathVariable int id) {
Ну тут на самом деле очень спорно. Чтобы не было ошибкок копи-пасты вероятно есть смысл в простых случах исользовать имена id и даже object. Встречал этот подход в реальных проектах.

2023-04-19 19:49 UTC, VasilyNS commented
Привет! Что смогли оперативно попроваить по твоим рекомендациям, поправили!

>Рекомендую логи с индентификатором алгоритма делать до запроса в бд тк если у вас что-то упадет в бд вы даже не узнаете какой алгоритм виноват в ошибках

Согласен. Тут очень многое зависит от требований к логированию. Чтобы не завалило логами. В нашем случает логируется сам вход в контоллер, вплоть то url и передаваемого объекта. В реальности вероятно понадобится логирование и начала операции/транзакции и её успешное завершение. Причем не в консоль, а как когда то я делал в отдельную базу на отдельном кластере, чтобы был быстрый доступ к логам и их анализ.

> Когда пишете sql запрос лучше разбивать его на логические блоки по строкам, а то тяжко читать по 1 слову на строке

Принято! Старались делать красиво, но еще студенты! )

> Что можете поправить если есть время и желание:
> 
> id - это плохое название переменной в методах, у нас десятки сущностей и у каждой айди и зачем делать предположение что это допустим директор_айди если можно так сразу написать. А в реальном приложение этих айди бывает еще по 2-3 у каждой сущности вообще будет больно.

Согласен в случае, когда в методе идет операции со многими сущностями со своими id. Есть это что-то простое, то встречал на практике унификацию название полей и методов. id, object и т.п. для уменьшения ошибок копи-пасты.

>В именах методов сервиса я рекомендую делать так find - возвращает или объект или null, а get возвращает всегда объект или исключение. Это дает стандарт для команды разработки и понимание как ведет себя метод.

Да, не досмотрел один метод, исправлено! )

> Написал что можно исправить/улучшить, но в целом если есть усталость или сроки горят работа, то можете не переживать работа готова для зачета - так что исправляйте на что есть время и буду ждать с правками =) 

Спасибо за развернутые комменты!!! Максимально всё поправили, что успели. Итак, версия 3! ))

2023-04-20 05:35 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу что-то поправлено, что-то не очень))  но в целом на зачет тут есть - зачет!

Хорошая работа =)

2023-04-20 05:35 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDao.java
> +    void checkFilm(int id);
checkExistFilm

2023-04-20 05:35 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDao.java
> +    void checkUser(int id);
checkExistUser

2023-04-20 05:35 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/enums/FilmSearchBy.java
> +public enum FilmSearchBy {
Вроде нигде не используется =)

2023-04-20 11:40 UTC, merged