feat:все условия ТЗ выполнены
VasilyNS/java-filmorate pull request #3
Opened 2023-02-14 10:37 UTC by VasilyNS

2023-02-15 14:07 UTC, krylov-sergey-sergeevich requested changes
Привет, в целом код хороший, давай сделаем его лучше:

1) Исправить то что в коде указал
2) Логи на англ давай переведем
3) Все текста в исключениях должны быть на англ языке

Буду ждать с доработками =)

2023-02-15 14:07 UTC, krylov-sergey-sergeevich commented on HELP.md
> +# Getting Started
Этот файл надо в gitignore добавить и удалить из pr

2023-02-15 14:07 UTC, krylov-sergey-sergeevich commented on .mvn/wrapper/maven-wrapper.properties
> +distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.8.6/apache-maven-3.8.6-bin.zip
Этот и файл рядом в папке обычно в github не добавляют, но не критично

2023-02-15 14:07 UTC, krylov-sergey-sergeevich commented on mvnw
> +#!/bin/sh
Этот файл надо в gitignore добавить и удалить из pr

2023-02-15 14:07 UTC, krylov-sergey-sergeevich commented on pom.xml
> +			<artifactId>logbook-spring-boot-starter</artifactId>
Для чего эта зависимость?

2023-02-15 14:07 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/constant/Constants.java
> +    final public static LocalDate FIRST_FILM_DATE = LocalDate.of(1895,12,28);
разве не другая последовательность модификаторов доступа должна быть?

2023-02-15 14:07 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    Integer id = 1;
Модификаторы доступа

2023-02-15 14:07 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    Integer id = 1;
Модификаторы доступа

2023-02-15 14:07 UTC, krylov-sergey-sergeevich commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    Film film;
Модификаторы доступа

2023-02-15 14:07 UTC, krylov-sergey-sergeevich commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +    User user;
Модификаторы доступа

2023-02-15 14:07 UTC, krylov-sergey-sergeevich commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> + * Аннотация для класса @SpringBootTest нужна для запуска SpringBoot
А зачем тут это написано если аннотации нет ? =)

2023-02-15 14:07 UTC, krylov-sergey-sergeevich commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +class FilmControllerTest {
Еще таким способом можно тесты писать:
```java
import javax.validation.*;

ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
validator = factory.getValidator();

@Test

public void invalidName() {

	film = Film.builder().name("")
	
			.description("qweq")
			
			.duration(120)
			
			.releaseDate(LocalDate.of(1999, 12, 12))
			
			.build();
	
	violations = validator.validate(film);
	
	  
	
	assertFalse(violations.isEmpty(), violations.toString());
	
	violations.clear();

}
```

2023-02-15 16:40 UTC, VasilyNS commented on pom.xml
> +			<artifactId>logbook-spring-boot-starter</artifactId>
> 

Это библиотека из теории (Спринт 9 → Тема 5: Логирование → Урок 5 Логируем свои сообщения) для самого детального логирования запросов. Решил подключить, раз про неё была информация: 

Наконец, третий способ — использовать стороннюю библиотеку. Одна из таких библиотек — LogBook. Добавить её довольно просто. Для этого необходимо создать следующую зависимость:
<dependency>
    <groupId>org.zalando</groupId>
    <artifactId>logbook-spring-boot-starter</artifactId>
    <version>2.14.0</version>
</dependency> 
Логирование происходит с уровнем TRACE, поэтому для отображения логов также необходимо изменить уровень логирования соответствующего пакета:
logging.level.org.zalando.logbook=TRACE 
Результат — логирование входящих и исходящих запросов в формате JSON: ....

2023-02-15 16:42 UTC, VasilyNS commented on src/main/java/ru/yandex/practicum/filmorate/constant/Constants.java
> +    final public static LocalDate FIRST_FILM_DATE = LocalDate.of(1895,12,28);
да, константы немного не так из теории выглядят ))
public static final double PI = 3.14;
исправлено

2023-02-15 16:44 UTC, VasilyNS commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    Integer id = 1;
сделано, private Integer id = 1;

2023-02-15 16:45 UTC, VasilyNS commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> + * Аннотация для класса @SpringBootTest нужна для запуска SpringBoot
убрал, это лишее, согласен )

2023-02-15 16:46 UTC, VasilyNS commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +    User user;
ok, private User user;

2023-02-15 16:46 UTC, VasilyNS commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    Film film;
ok, private Film film;

2023-02-15 16:48 UTC, VasilyNS commented on mvnw
> +#!/bin/sh
ок, убрал. И файл mvnw.cmd тогда тоже выкинуть?

2023-02-15 17:02 UTC, VasilyNS commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +class FilmControllerTest {
понял, принял! фабричный метод.

2023-02-15 17:07 UTC, VasilyNS commented on .mvn/wrapper/maven-wrapper.properties
> +distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.8.6/apache-maven-3.8.6-bin.zip
В ветке main, которая пришла от Яндекса, изначально в гитингоре есть строчка 
!.mvn/wrapper/maven-wrapper.jar
как я понял, эти файлы важные для отправки на гитхаб, и файл maven-wrapper.properties вроде тоже в игноре не прописан.

2023-02-15 17:07 UTC, VasilyNS commented on HELP.md
> +# Getting Started
понял, убрал

2023-02-15 18:16 UTC, VasilyNS commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    Integer id = 1;
ok, private Integer id = 1;

2023-02-16 05:38 UTC, krylov-sergey-sergeevich commented on mvnw
> +#!/bin/sh
Ага

2023-02-16 05:41 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

2023-02-16 11:47 UTC, merged