Задание готово по ТЗ 10
VasilyNS/java-filmorate pull request #4
Opened 2023-02-22 20:33 UTC by VasilyNS

Старался, чтобы в коде всё было идеально, но как всегда что-то мог не увидеть )

2023-02-23 04:13 UTC, krylov-sergey-sergeevich requested changes
Привет, в целом неплохая работа, давай поправим то что отметил и еще пару моментов:
1) **Учесть и поправить нейминг методов:** get - это или получение объекта или исключение, find - это или объект или null
2.  Давай вместо конструктора будем аннотацию из ломбока использовать [@requiredargsconstructor](https://github.com/requiredargsconstructor)
3. А валидация разве вся которая необходима есть? Ощущение что чего-то не хватает, но могу ошибаться

На счет исключений в будущем все равно придется создать более специализированные исключения. Поэтому рекомендую сразу думать о том чтобы для каждого типа ситуаций создавать исключение, например
UserNotFound(id)
FilmNotFound(id)

Буду ждать с правками =)

2023-02-23 04:13 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmStorage filmStorage, FilmService filmService) {
Давай добавим аннотацию от ломбок для того чтобы конструктор не писать

2023-02-23 04:13 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    UserController(UserStorage userStorage, UserService userService) {
Давай добавим аннотацию от ломбок для того чтобы конструктор не писать

2023-02-23 04:13 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(FilmStorage filmStorage, UserService userService) {
Давай добавим аннотацию от ломбок для того чтобы конструктор не писать

2023-02-23 04:13 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserService(UserStorage userStorage) {
Давай добавим аннотацию от ломбок для того чтобы конструктор не писать

2023-02-23 04:13 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            throw new ObjectNotFoundException("No movie with this id");
Каким id? Исключение должно быть говорящим, надо добавить в него айди

2023-02-23 04:13 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            throw new ObjectNotFoundException("No film with this id");
Каким id? Исключение должно быть говорящим, надо добавить в него айди

2023-02-23 04:13 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +            throw new ObjectNotFoundException("No user with this id");
Каким id? Исключение должно быть говорящим, надо добавить в него айди

2023-02-23 04:13 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +            throw new ObjectNotFoundException("No user with this id");
Каким id? Исключение должно быть говорящим, надо добавить в него айди

2023-02-23 05:59 UTC, VasilyNS commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmStorage filmStorage, FilmService filmService) {
Сделано.

2023-02-23 05:59 UTC, VasilyNS commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    UserController(UserStorage userStorage, UserService userService) {
Сделано.

2023-02-23 06:00 UTC, VasilyNS commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(FilmStorage filmStorage, UserService userService) {
Сделано.

2023-02-23 06:00 UTC, VasilyNS commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserService(UserStorage userStorage) {
Сделано.

2023-02-23 06:00 UTC, VasilyNS commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            throw new ObjectNotFoundException("No movie with this id");
Сделано.

2023-02-23 06:00 UTC, VasilyNS commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            throw new ObjectNotFoundException("No film with this id");
Сделано.

2023-02-23 06:00 UTC, VasilyNS commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +            throw new ObjectNotFoundException("No user with this id");
Сделано.

2023-02-23 06:00 UTC, VasilyNS commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +            throw new ObjectNotFoundException("No user with this id");
Сделано.

2023-02-23 06:13 UTC, VasilyNS commented
> Привет, в целом неплохая работа, давай поправим то что отметил и еще пару моментов:

Спасибо за ревью! ) Очень полезные замечания!!!

Поправил:
* Добавлена аннотация @RequiredArgsConstructor вместо конструкторов с @Autowired в классах FilmService, UserService, FilmController, UserController
* Исправлены названия многих методов, которые начинались с "get", теперь get* - это или получение объекта или исключение, find* - это или объект или null
* Исключение ObjectNotFound разделено на два: UserNotFound и FilmNotFound
* В текст исключений об отсутствии пользователя или фильма добавлен вывод id запрашиваемого объекта


По валидации, она у меня строго по ТЗ финалок спринта 9 и 10, иначе бы тесты не прошли! )
В новых методах для реализации новых эндпоинтов всё получается автоматически при обращению к пользователям и фильмам по их id, при отсутствии объектов или если вместо чисел в URL символы или отрицательные значения - тоже срабатывают соответствующие исключения, выдаются правильные коды ошибок и верные записи в лог.

У меня даже немного больше валидации, чем нужно для тестов!!!
Например, в JS-тестах постмана нет проверок насчет того, что можно поставить лайк фильму от несуществующего пользователя. И этот проект пройдет тесты!!! А я в своём коде это проверяю ))
Я не знаю, что можно подсунуть этому коду через API, чтобы он повел себя вне штатных исключений, вроде я всё проверил, что только можно )

2023-02-24 17:32 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

2023-02-24 17:35 UTC, krylov-sergey-sergeevich approved these changes
Все хорошо - зачет!

2023-02-24 17:35 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    Collection<User> findAll() {
Все же все контроллеры они возвращают или что-то или исключение поэтому к ним применимо get и даже если ответ пустой это ответ (для списка)

2023-02-24 17:35 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +            throw new UserNotFoundException("No user with id=" + user.getId());
Попробуй подумать как сделать так чтобы в следующем дз было вот так:
throw new UserNotFoundException(user.getId()); - но чтобы текст исключения по сути для пользователя не изменился



(подсказка ниже если не придумаешь)


нужно изменить конструктор в исключение

2023-03-20 08:07 UTC, VasilyNS commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    Collection<User> findAll() {
Готово. Контроллеры для "/users" переименованы в getAll, getCommonFriends, getFriends. Аналогично по фильмим.

2023-03-20 08:07 UTC, VasilyNS commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +            throw new UserNotFoundException("No user with id=" + user.getId());
Готово. Изменены форматы пользвательских исключений на FilmNotFoundException(int id) и UserNotFoundException(int id)

2023-03-20 08:15 UTC, VasilyNS commented
Сливаем ветки [main] и [add-friends-likes]

2023-03-20 08:15 UTC, closed without merging