Все условия ТЗ 11 выполнены, отправлено на ревью
VasilyNS/java-filmorate pull request #6
Opened 2023-03-24 11:05 UTC by VasilyNS

Все условия ТЗ 11 выполнены, проект проходит все тесты postman для sprint11/add-database, а при переключении на старые бины "InMemory" - проходит тесты postman для sprint10/add-friends-likes. Добавлено интеграционное тестирование, все публичные методы имплементаций интерфейсов DAO покрыты тестами.

Комментарии добавлены только к сложным неоднозначным фрагментам кода и настроек.

Трудозатраты - 4 полных рабочих дня ))

2023-03-25 07:37 UTC, krylov-sergey-sergeevich requested changes
Привет, неплохо, давай обсудим:
1) Логи добавить в контроллеры
2) (value =  в контроллерах не обязателен 
3) Обсудить моменты которые еще по коду отметил

- Рекомендую почитать про swagger для красивого оформления того что делают контроллеры он очень кстати (но это не обязательно)
- Ин мемори версию на самом деле можно потихоньку удалять

2023-03-25 07:37 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/dao/GenreDao.java
> +public interface GenreDao {
Давай немного пустыми строками разделим чтобы глаза не слипались

2023-03-25 07:37 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +            popFilms.add(getById(popId));
Те у нас в бд будет теоретически много запросов? Может вместо цикла сделать 1 сложный запрос?

2023-03-25 07:37 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/GenreDaoImpl.java
> +                jdbcTemplate.update(sql, filmId, genre.getId());
Надо не забывать что тут цикл и теоретически может быть много запросов

2023-03-25 15:37 UTC, VasilyNS commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/GenreDaoImpl.java
> +                jdbcTemplate.update(sql, filmId, genre.getId());
- Про коммент: "Надо не забывать что тут цикл и теоретически может быть много запросов" – да, тут цикл, ведь по API к нам приходят много жанров для одного фильма. Один жанр – одна вставка записи через INSERT в таблицу жанров для фильма. В этой таблице используется составной ключ (film_id, genre_id), поэтому СУБД не даст сохранить дублирующиеся жанры для одного и того же фильма, проверка на них есть в тестах постмана ("genres": [{ "id": 1}, { "id": 2}, { "id": 1}]). Сейчас запустил более крутой проверочный пример:  "genres": [{ "id": 1}, { "id": 1}, { "id": 1}, { "id": 1}, { "id": 3}, { "id": 1}, { "id": 1}, { "id": 4}, { "id": 5}, { "id": 1}]. Запись в базу отработала корректно, возвращается объект с: "genres":[{"id":1,"name":"Комедия"},{"id":3,"name":"Мультфильм"},{"id":4,"name":"Триллер"},{"id":5,"name":"Документальный"}]

2023-03-25 15:38 UTC, VasilyNS commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +            popFilms.add(getById(popId));
Переписал код. Да, можно сделать селект, который выведет таблицу со всеми колонками, аналогично как для метода findAllFilms, и вместо цикла по id с составлением списка через .add(getById(popId)) и мы просто воспользуемся уже имеющимся методом makeFilm. По количеству операций и алгоритмической сложности то на то и выходит, хотя код Java будет компактнее за счет удлинения селекта, но пусть будет так, переделал. На самом деле, селект тоже стал короче! Так как методы типа rs.getInt("film_id") прекрасно принимают значения столбцов вида "f.film_id", не пришлось писать гигантскую конструкцию для всех столбцов "SELECT f.film_id AS film_id, f.name AS name, .........…", хватило "SELECT f.*.

2023-03-25 15:38 UTC, VasilyNS commented on src/main/java/ru/yandex/practicum/filmorate/dao/GenreDao.java
> +public interface GenreDao {
Прошелся по всему коду и в больших методах разделил логические блоки через перевод строки. Полностью согласен, кое-где разделений пустой строкой не хватало.

2023-03-25 15:41 UTC, VasilyNS commented
Версия 2, ТЗ спринт 11. Сильно переработал код:

- Удалены необязательные "value =" в контроллерах.

- Удалена совместимость c "InMemory"-версией из спринта 10: старые бины, а также лишние поля и методы из POJO-классов модели. В итоге полностью избавился от конструкторов этих классах, всё через аннотации.

- Прошелся по всему коду и в больших методах разделил логические блоки через перевод строки. Полностью согласен, кое-где разделений пустой строкой не хватало.

- Прочитал несколько статей про Swagger, спасибо за совет! Да, очень интересный инструмент для документирования API! Внес его к себе в конспекты курса и обязательно добавлю чуть позже. Наставник призывал пока не усложнять проект, чтобы не было проблем на групповой работе.

- Про логи, на замечание: " Логи добавить в контроллеры" – у меня логирование 1) включено через logbook максимального уровня (TRACE);  2) через @Slf4j и log.info("…"); ведется бинах-имплементациях DAO о всех успешных операциях  3) через log.warn(e.getMessage()); добавлено в методы класса ErrorHandler. Обязательно ли еще в контроллерах добавлять логирование?

- Про коммент: "Надо не забывать что тут цикл и теоретически может быть много запросов" – да, тут цикл, ведь по API к нам приходят много жанров для одного фильма. Один жанр – одна вставка записи через INSERT в таблицу жанров для фильма. В этой таблице используется составной ключ (film_id, genre_id), поэтому СУБД не даст сохранить дублирующиеся жанры для одного и того же фильма, проверка на них есть в тестах постмана `("genres": [{ "id": 1}, { "id": 2}, { "id": 1}]).` Сейчас запустил более крутой проверочный пример:  `"genres": [{ "id": 1}, { "id": 1}, { "id": 1}, { "id": 1}, { "id": 3}, { "id": 1}, { "id": 1}, { "id": 4}, { "id": 5}, { "id": 1}]`. Запись в базу отработала корректно, возвращается объект с: `"genres":[{"id":1,"name":"Комедия"},{"id":3,"name":"Мультфильм"},{"id":4,"name":"Триллер"},{"id":5,"name":"Документальный"}]`

- Про коммент: "Те у нас в бд будет теоретически много запросов? Может вместо цикла сделать 1 сложный запрос?" Переписал код. Да, можно сделать селект, который выведет таблицу со всеми колонками, аналогично как для метода findAllFilms, и вместо цикла по id с составлением списка через .add(getById(popId)) и мы просто воспользуемся уже имеющимся методом makeFilm. По количеству операций и алгоритмической сложности то на то и выходит, хотя код Java будет компактнее за счет удлинения селекта, но пусть будет так, переделал. На самом деле, селект тоже стал короче! Так как методы типа rs.getInt("film_id") прекрасно принимают значения столбцов вида "f.film_id", не пришлось писать гигантскую конструкцию для всех столбцов "SELECT f.film_id AS film_id, f.name AS name, .........…", хватило "SELECT f.*.

- Сам уже понял и переделал метод makeFilm, в первой версии он не использовал уже имеющиеся хорошие методы по работе с рейтингом и жанрами! В первой версии я написал лишний код и всё продублировал лишними сетами и циклом. Сейчас код стал намного компактнее, красивее и понятнее.

Было много лишнего:

```
    private Film makeFilm(ResultSet rs) throws SQLException {
        Film film = new Film(
                rs.getInt("film_id"),
                rs.getString("name"),
                rs.getString("description"),
                rs.getDate("release_date").toLocalDate(),
                rs.getInt("duration")
        );

        // Добавляем в объект фильма объект mpa с id и именем рейтинга, имя рейтинга mpa читается из базы
        int mpa_id = rs.getInt("rating_id");
        Mpa mpa = mpaDao.getMpaById(mpa_id);
        film.setMpa(mpa);

        // Считываем все жанры для конкретного фильма из базы
        List<Genre> gs = genreDao.findAllGenresForFilm(film.getId());

        // Создаем массив справочника жанров (id жанра, имя жанра) для конкретного фильма
        List<GenreBook> gsForFilm = new ArrayList<>();
        for (Genre g : gs) {
            GenreBook gForFilm = new GenreBook(g.getGenreId(), genreDao.getGenreNameById(g.getGenreId()));
            gsForFilm.add(gForFilm);
        }

        // Записываем полученный массив жанров в фильм
        film.setGenres(gsForFilm);
        return film;
    }
```

Стало просто красиво:

```
    private Film makeFilm(ResultSet rs) throws SQLException {
         Film film = new Film()
                 .setId(rs.getInt("film_id"))
                 .setName(rs.getString("name"))
                 .setDescription(rs.getString("description"))
                 .setReleaseDate(rs.getDate("release_date").toLocalDate())
                 .setDuration(rs.getInt("duration"))
                 .setMpa(mpaDao.getMpaById(rs.getInt("rating_id")))
                 .setGenres(genreDao.findAllGenresForFilm( rs.getInt("film_id") ));
        return film;
    }
```

У нас тут простой класс и билдер использовать нет смысла, хватит и каскадных set (билдера на минималках), которые можно использовать после @Accessors(chain = true) в классе модели.

2023-03-26 13:48 UTC, krylov-sergey-sergeevich approved these changes
Привет, зачет. Крутой развернутый комментарий от тебя, за него прям лайк

- На счет логов, если тебе хватает, то это хорошо, но в своей работе я стараюсь во всех контроллерах писать еще свой лог (вообщем на вкус и цвет)
- На счет алгоритмической сложности не уверен, надо смотреть

И обычно на продакшене не включают Trace режим из-за него ООООЧЕНЬ много логов обычно идет и с ним тяжко)

2023-03-26 17:43 UTC, merged